// client/src/pages/App/App.tsx
import { useEffect, useState } from 'react';
import { AppService } from '../../services/App.service';
import './App.css';

function App() {
	const [ frontImageHidden, setFrontImageHidden ] = useState(false);
	const [ images, setImages ] = useState([]);
	const [ backImage, setBackImage ] = useState('');
	const [ frontImage, setFrontImage ] = useState('');
	const [ transitionTime ] = useState(5);
	const [ animationTime ] = useState(2);
	const [ index, setIndex ] = useState(0);

	useEffect(() => {
		const getImages = async () => {
			const appService = new AppService();
			const { data } = await appService.getImages();
			setImages(data);
			setBackImage(`http://localhost:5000/albums/image/${data[index]['_id']}`);
			setIndex(1);
			setFrontImage(`http://localhost:5000/albums/image/${data[index]['_id']}`);
		};

		getImages();
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, []);

	useEffect(
		() => {
			const interval = setInterval(() => {
				//console.log(`This will run each ${transitionTime} second!`);
				setBackAndFrontImages();
			}, 1000 * transitionTime);

			const setBackAndFrontImages = () => {
				if (images.length) {
					setFrontImageHidden(!frontImageHidden);
					const timer = setTimeout(() => {
						setIndex(index + 1 >= images.length ? 0 : index + 1);
						//console.log(`This will run after ${animationTime} second!`, `current index ${index} of ${images.length}`);
						if (frontImageHidden) {
							setFrontImage(`http://localhost:5000/albums/image/${images[index]['_id']}`);
						} else {
							setBackImage(`http://localhost:5000/albums/image/${images[index]['_id']}`);
						}
						clearTimeout(timer);
					}, 1000 * animationTime);
				}
			};
			return () => clearInterval(interval);
		},
		[ animationTime, frontImageHidden, images, index, transitionTime ]
	);

	return (
		<div className="container">
			<div
				className="background"
				style={{ backgroundImage: frontImageHidden ? `url(${frontImage})` : `url(${backImage})` }}
			>
				<img
					className={`${frontImageHidden ? 'fade-out' : 'fade-in'}`}
					style={{ animationDuration: `${animationTime}s` }}
					src={backImage}
					alt={backImage}
				/>
				<img
					className={`${!frontImageHidden ? 'fade-out' : 'fade-in'}`}
					style={{ animationDuration: `${animationTime}s` }}
					src={frontImage}
					alt={frontImage}
				/>
			</div>
			<div
				className={`image-container ${frontImageHidden ? 'fade-out' : 'fade-in'}`}
				style={{ animationDuration: `${animationTime}s` }}
			>
				<img src={backImage} alt={backImage} />
			</div>
			<div
				className={`image-container ${!frontImageHidden ? 'fade-out' : 'fade-in'}`}
				style={{ animationDuration: `${animationTime}s` }}
			>
				<img src={frontImage} alt={frontImage} />
			</div>

			{/* <pre>frontImageHidden = {frontImageHidden.toString()}</pre>
			<pre>transitionTime = {transitionTime}</pre>
			<pre>animationTime = {animationTime}</pre>
			<pre>index = {index}</pre>
			<input
				type="number"
				name="transitionTime"
				id="transitionTime"
				value={transitionTime}
				onChange={(e) => setTransitionTime(e.target.valueAsNumber)}
			/>
			<input
				type="number"
				name="animationTime"
				id="animationTime"
				value={animationTime}
				onChange={(e) => setAnimationTime(e.target.valueAsNumber)}
			/> */}
		</div>
	);
}

export default App;

// client/src/routes/App.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { AppService } from "../services/App.service";

	let frontImageHidden = false;
	let images = [];
	let backImage = "";
	let frontImage = "";
	let transitionTime = 5;
	let animationTime = 2;
	let index = 0;

	onMount(async () => {
		const appService = new AppService();
		const data: any[] = await appService.getImages();
		if (data.length) {
			images = data;
			backImage = `${process.env.serverUrl || "http://localhost:5000"}/albums/image/${data[index]["id"]}`;
			index = 1;
			frontImage = `${process.env.serverUrl || "http://localhost:5000"}/albums/image/${data[index]["id"]}`;
		}

		setInterval(() => {
			//console.log(`This will run each ${transitionTime} second!`);
			setBackAndFrontImages();
		}, 1000 * transitionTime);
	});

	const setBackAndFrontImages = () => {
		if (images.length) {
			frontImageHidden = !frontImageHidden;
			index = index + 1 >= images.length ? 0 : index + 1;
			//console.log(`This will run after ${animationTime} second!`, `current index ${index} of ${images.length}`);
			if (frontImageHidden) {
				frontImage = `${process.env.serverUrl || "http://localhost:5000"}/albums/image/${images[index]["id"]}`;
			} else {
				backImage = `${process.env.serverUrl || "http://localhost:5000"}/albums/image/${images[index]["id"]}`;
			}
		}
	};
</script>

<div class="container">
	<div
		class="background"
		style="background-image: {frontImageHidden
			? `url(${frontImage})`
			: `url(${backImage})`}"
	>
		<img
			class={`${frontImageHidden ? "fade-out" : "fade-in"}`}
			style="animation-duration: {`${animationTime}s`}"
			src={backImage}
			alt={backImage}
		/>
		<img
			class={`${!frontImageHidden ? "fade-out" : "fade-in"}`}
			style="animation-duration: {`${animationTime}s`}"
			src={frontImage}
			alt={frontImage}
		/>
	</div>
	<div
		class={`image-container ${frontImageHidden ? "fade-out" : "fade-in"}`}
		style="animation-duration: {`${animationTime}s`}"
	>
		<img src={backImage} alt={backImage} />
	</div>
	<div
		class={`image-container ${!frontImageHidden ? "fade-out" : "fade-in"}`}
		style="animation-duration: {`${animationTime}s`}"
	>
		<img src={frontImage} alt={frontImage} />
	</div>
</div>

<style>
	.container {
		width: 100vw;
		height: 100vh;
		background-color: black;
	}

	.image-container {
		position: absolute;
		left: 50%;
		top: 50%;
		transform: translate(-50%, -50%);
		max-height: 100vh;
		max-width: 100vw;
	}

	.background {
		position: absolute;
		width: 100vw;
		height: 100vh;
		background-repeat: no-repeat;
		background-size: cover;
		-webkit-filter: blur(5px);
		-moz-filter: blur(5px);
		-o-filter: blur(5px);
		-ms-filter: blur(5px);
		filter: blur(5px);
	}

	.background > img {
		position: absolute;
		top: 0;
		left: 0;
		width: 100vw;
		height: 100vh;
		cursor: none;
	}

	.fade-in {
		animation: fade-in;
	}

	.fade-out {
		animation: fade-out;
	}

	.fade-in,
	.fade-out {
		animation-fill-mode: forwards;
	}

	img {
		max-height: 100vh;
		max-width: 100vw;
		cursor: none;
	}

	@keyframes fade-out {
		from {
			opacity: 100%;
		}
		to {
			opacity: 0%;
		}
	}

	@keyframes fade-in {
		from {
			opacity: 0%;
		}
		to {
			opacity: 100%;
		}
	}
</style>
